name: Tests Cabal

on:
  push:
    branches:
    - master
    paths:
      - 'src/**'
      - 'test/**'
      - 'quickjs/**'
      - 'stack.yaml'
      - 'quickjs-hs.cabal'
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plan:
          - { ghc: "8.10.4", cabal: "3.2.1" }
          - { ghc: "9.2.4", cabal: "3.6.3" }
    env:
      CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: haskell/actions/setup@v1
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.plan.ghc }}
          cabal-version: ${{ matrix.plan.cabal }}
      - run: cabal v2-update
      - run: cabal v2-freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.plan.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.plan.ghc }}-
      - run: cabal v2-build $CONFIG
      - run: cabal v2-test $CONFIG
